-- Distribuciones LYM - esquema inicial Supabase
-- Ejecutar en Supabase SQL Editor.

create extension if not exists pgcrypto;

create type public.product_status as enum (
  'pending_price',
  'published',
  'hidden',
  'on_request',
  'offer_active',
  'needs_cleanup'
);

create type public.availability_status as enum (
  'available_to_confirm',
  'check_availability',
  'on_request',
  'temporarily_unavailable'
);

create type public.order_status as enum (
  'payment_pending',
  'paid',
  'preparing',
  'in_delivery',
  'delivered',
  'cancelled'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  phone text,
  role text not null default 'customer' check (role in ('customer', 'admin', 'seller', 'courier')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  category text not null,
  price integer,
  unit text not null default 'Unidad',
  stock integer not null default 0,
  availability public.availability_status not null default 'check_availability',
  tag text,
  image_url text,
  status public.product_status not null default 'pending_price',
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.offers (
  id bigint generated by default as identity primary key,
  title text not null,
  target text not null,
  discount text not null,
  product_id bigint references public.products(id) on delete set null,
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.customer_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  receiver_name text not null,
  phone text not null,
  address text not null,
  neighborhood text,
  notes text,
  zone text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  code text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_phone text,
  status public.order_status not null default 'payment_pending',
  delivery_method text not null,
  delivery_address text,
  delivery_zone text,
  delivery_cost integer default 0,
  subtotal integer default 0,
  total integer default 0,
  wompi_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer,
  total integer
);

create table public.delivery_assignments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  courier_name text not null,
  cost integer,
  delivery_window text,
  notes text,
  sent_to_customer boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.offers enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_assignments enable row level security;
alter table public.audit_log enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant select on public.offers to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.customer_addresses to authenticated;
grant select, insert on public.orders to authenticated;
grant select, insert on public.order_items to authenticated;
grant select on public.delivery_assignments to authenticated;
grant select, insert on public.audit_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Productos publicados visibles"
on public.products for select
using (status in ('published', 'offer_active', 'on_request'));

create policy "Admin gestiona productos"
on public.products for all
using (public.is_admin())
with check (public.is_admin());

create policy "Ofertas activas visibles"
on public.offers for select
using (active = true);

create policy "Admin gestiona ofertas"
on public.offers for all
using (public.is_admin())
with check (public.is_admin());

create policy "Cliente ve su perfil"
on public.profiles for select
using (auth.uid() = id);

create policy "Admin ve perfiles"
on public.profiles for select
using (public.is_admin());

create policy "Admin actualiza perfiles"
on public.profiles for update
using (public.is_admin())
with check (public.is_admin());

create policy "Cliente actualiza su perfil"
on public.profiles for update
using (auth.uid() = id);

create policy "Cliente ve sus direcciones"
on public.customer_addresses for select
using (auth.uid() = user_id);

create policy "Cliente gestiona sus direcciones"
on public.customer_addresses for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Cliente ve sus pedidos"
on public.orders for select
using (auth.uid() = user_id);

create policy "Admin gestiona pedidos"
on public.orders for all
using (public.is_admin())
with check (public.is_admin());

create policy "Cliente ve items de sus pedidos"
on public.order_items for select
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
    and orders.user_id = auth.uid()
  )
);

create policy "Admin gestiona items de pedidos"
on public.order_items for all
using (public.is_admin())
with check (public.is_admin());

create policy "Cliente ve domicilio de sus pedidos"
on public.delivery_assignments for select
using (
  exists (
    select 1 from public.orders
    where orders.id = delivery_assignments.order_id
    and orders.user_id = auth.uid()
  )
);

create policy "Admin gestiona domicilios"
on public.delivery_assignments for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admin ve auditoria"
on public.audit_log for select
using (public.is_admin());

create policy "Admin crea auditoria"
on public.audit_log for insert
with check (public.is_admin());
