export type Product = {
  id: number;
  name: string;
  category: string;
  price: number | null;
  unit: string;
  stock: number;
  tag: string;
  image: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Ácido muriático por galón L&M",
    category: "Control pH",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Control pH",
    image: "/products/acido-muriatico-por-galon-l-y-m.png",
  },
  {
    id: 2,
    name: "Ácido tricloroisocianúrico granulado al 91% Marclor",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/acido-tricloroisocianurico-granulado-al-91-marclor.png",
  },
  {
    id: 3,
    name: "Adhesivo Marimex",
    category: "Adhesivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Adhesivos",
    image: "/products/adhesivo-marimex.png",
  },
  {
    id: 4,
    name: "Alguicida Alquiplus",
    category: "Alguicidas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Alguicidas",
    image: "/products/alguicida-alquiplus.png",
  },
  {
    id: 5,
    name: "Alguicida Induneth",
    category: "Alguicidas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Alguicidas",
    image: "/products/alguicida-induneth.png",
  },
  {
    id: 6,
    name: "Alguicida Plus",
    category: "Alguicidas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Alguicidas",
    image: "/products/alguicida-plus.png",
  },
  {
    id: 7,
    name: "Alka Incrementador de alcalinidad x 20 kg",
    category: "Adhesivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Adhesivos",
    image: "/products/alka-incrementador-de-alcalinidad-x-20-kg.jpg",
  },
  {
    id: 8,
    name: "Alkadur en polvo L&M",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/alkadur-en-polvo-l-y-m.png",
  },
  {
    id: 9,
    name: "Alkalos en tarro Cloridex",
    category: "Control pH",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Control pH",
    image: "/products/alkalos-en-tarro-cloridex.png",
  },
  {
    id: 10,
    name: "Analizador de cloro libre y pH Lamotte",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/analizador-de-cloro-libre-y-ph-lamotte.png",
  },
  {
    id: 11,
    name: "Aro salvavidas para piscina",
    category: "Seguridad",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Seguridad",
    image: "/products/aro-salvavidas-para-piscina.png",
  },
  {
    id: 12,
    name: "Asesponja kit X 2",
    category: "Mantenimiento",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Mantenimiento",
    image: "/products/asesponja-kit-x-2.png",
  },
  {
    id: 13,
    name: "Aspiradora Flexible De 14 pulg Panda",
    category: "Aspiradores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Aspiradores",
    image: "/products/aspiradora-flexible-de-14-pulg-panda.png",
  },
  {
    id: 14,
    name: "Bacterias para pozos sépticos Biodyne 301",
    category: "Pozos sépticos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Pozos sépticos",
    image: "/products/bacterias-para-pozos-septicos-biodyne-301.png",
  },
  {
    id: 15,
    name: "Bala LED luminaria de piso de 3W para exterior",
    category: "Luces",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Luces",
    image: "/products/bala-led-luminaria-de-piso-de-3w-para-exterior.png",
  },
  {
    id: 16,
    name: "Bala Sumergible Led 12w Luz Rgb Para Piscinas-Jacuzzis",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/bala-sumergible-led-12w-luz-rgb-para-piscinas-jacuzzis.png",
  },
  {
    id: 17,
    name: "Bala sumergible LED de 24W con luz cálida",
    category: "Luces",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Luces",
    image: "/products/bala-sumergible-led-de-24w-con-luz-calida.png",
  },
  {
    id: 18,
    name: "Blower Industrial Maaax Pump 1.2 HP 220v",
    category: "Blowers",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Blowers",
    image: "/products/blower-industrial-maaax-pump-1-2-hp-220v.jpg",
  },
  {
    id: 19,
    name: "Blower Ultra 9000 1hp/2hp a 110/220v",
    category: "Blowers",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Blowers",
    image: "/products/blower-ultra-9000-1hp-2hp-a-110-220v.jpg",
  },
  {
    id: 20,
    name: "Bomba mini smarth",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/bomba-mini-smarth.png",
  },
  {
    id: 21,
    name: "Boquilla de inyección ASTRAL",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/boquilla-de-inyeccion-astral.png",
  },
  {
    id: 22,
    name: "Boquilla de inyección sin escudo",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/boquilla-de-inyeccion-sin-escudo.png",
  },
  {
    id: 23,
    name: "Boquilla sin escudo de 1/8",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/boquilla-sin-escudo-de-1-8.png",
  },
  {
    id: 24,
    name: "Boquilla succión 1-1/2 aspiración roscada",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/boquilla-succion-1-1-2-aspiracion-roscada.png",
  },
  {
    id: 25,
    name: "Border Cleaner Cloridex",
    category: "Limpiadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Limpiadores",
    image: "/products/border-cleaner-cloridex.png",
  },
  {
    id: 26,
    name: "Caja de andén cuadrada",
    category: "Accesorios",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Accesorios",
    image: "/products/caja-de-anden-cuadrada.png",
  },
  {
    id: 27,
    name: "Carcasa de 20 pulgadas para filtro de agua Big Blu",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/carcasa-de-20-pulgadas-para-filtro-de-agua-big-blu.png",
  },
  {
    id: 28,
    name: "Carcasa de agua transparente Globalwater",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/carcasa-de-agua-transparente-globalwater.png",
  },
  {
    id: 29,
    name: "Carro Aspirador 12 ruedas negra",
    category: "Aspiradores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Aspiradores",
    image: "/products/carro-aspirador-12-ruedas-negra.png",
  },
  {
    id: 30,
    name: "Carro Aspirador 8 Ruedas negro",
    category: "Aspiradores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Aspiradores",
    image: "/products/carro-aspirador-8-ruedas-negro.png",
  },
  {
    id: 31,
    name: "Cartucho para filtro CC50",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/cartucho-para-filtro-cc50.png",
  },
  {
    id: 32,
    name: "Cascada de agua 90cm Emaux blanco",
    category: "Cascadas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cascadas",
    image: "/products/cascada-de-agua-90cm-emaux-blanco.png",
  },
  {
    id: 33,
    name: "Cascada en acero inoxidable L&M",
    category: "Cascadas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cascadas",
    image: "/products/cascada-en-acero-inoxidable-l-y-m.png",
  },
  {
    id: 34,
    name: "Cascada luz blanca L&M",
    category: "Cascadas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cascadas",
    image: "/products/cascada-luz-blanca-l-y-m.png",
  },
  {
    id: 35,
    name: "Cepillo aspirador esquinero",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-aspirador-esquinero.png",
  },
  {
    id: 36,
    name: "Cepillo curvo para piscinas de 18 pulg nylon Panda",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-curvo-para-piscinas-de-18-pulg-nylon-panda.png",
  },
  {
    id: 37,
    name: "Cepillo de 10 cerdas en acero",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-de-10-cerdas-en-acero.png",
  },
  {
    id: 38,
    name: "Cepillo De Acero 18 pulg",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-de-acero-18-pulg.png",
  },
  {
    id: 39,
    name: "Cepillo Nylon 18 cerdas plásticas mango en aluminio",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-nylon-18-cerdas-plasticas-mango-en-aluminio.png",
  },
  {
    id: 40,
    name: "Cepillo recto de 10 pulg cerdas nylon Panda",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-recto-de-10-pulg-cerdas-nylon-panda.png",
  },
  {
    id: 41,
    name: "Cepillo Triangular para Aspiradora",
    category: "Cepillos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cepillos",
    image: "/products/cepillo-triangular-para-aspiradora.png",
  },
  {
    id: 42,
    name: "Clarificante – T Clarit Plus Cloridex",
    category: "Clarificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Clarificadores",
    image: "/products/clarificante-t-clarit-plus-cloridex.png",
  },
  {
    id: 43,
    name: "Clarificante Induneth",
    category: "Clarificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Clarificadores",
    image: "/products/clarificante-induneth.png",
  },
  {
    id: 44,
    name: "Clarín L&M",
    category: "Clarificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Clarificadores",
    image: "/products/clarin-l-y-m.png",
  },
  {
    id: 45,
    name: "Clorador 2.5 Panda",
    category: "Dosificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Dosificadores",
    image: "/products/clorador-2-5-panda.png",
  },
  {
    id: 46,
    name: "Cloridex Acidet caneca",
    category: "Control pH",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Control pH",
    image: "/products/cloridex-acidet-caneca.png",
  },
  {
    id: 47,
    name: "Cloridex al 91% x Kg",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloridex-al-91-x-kg.jpg",
  },
  {
    id: 48,
    name: "Cloro al 91% caneca Clorizide",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/cloro-al-91-caneca-clorizide.png",
  },
  {
    id: 49,
    name: "Cloro granulado Super Choque Bolsa",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-super-choque-bolsa.jpg",
  },
  {
    id: 50,
    name: "Cloro granulado al 70% Aqua-Chlor",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-al-70-aqua-chlor.png",
  },
  {
    id: 51,
    name: "Cloro granulado al 70% caneca Aqua-Chlor",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-al-70-caneca-aqua-chlor.png",
  },
  {
    id: 52,
    name: "Cloro Granulado al 91% Marclor",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-al-91-marclor.jpg",
  },
  {
    id: 53,
    name: "Cloro Granulado bolsa Clorizide91",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-bolsa-clorizide91.png",
  },
  {
    id: 54,
    name: "Cloro granulado Districlor 70% L&M",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-districlor-70-l-y-m.png",
  },
  {
    id: 55,
    name: "Cloro granulado Super Choque Tarro",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/cloro-granulado-super-choque-tarro.jpg",
  },
  {
    id: 56,
    name: "Colorante Azul MAAAX",
    category: "Colorantes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Colorantes",
    image: "/products/colorante-azul-maaax.png",
  },
  {
    id: 57,
    name: "Corrector de Ph pH+ Caneca Cloridex",
    category: "Control pH",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Control pH",
    image: "/products/corrector-de-ph-ph-caneca-cloridex.png",
  },
  {
    id: 58,
    name: "Desengrasante HiClor",
    category: "Limpiadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Limpiadores",
    image: "/products/desengrasante-hiclor.png",
  },
  {
    id: 59,
    name: "Desnatador grande Astral",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/desnatador-grande-astral.png",
  },
  {
    id: 60,
    name: "Desnatador pequeño Haywar",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/desnatador-pequeno-haywar.png",
  },
  {
    id: 61,
    name: "Detergente multiuso desengrasante PQP",
    category: "Limpiadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Limpiadores",
    image: "/products/detergente-multiuso-desengrasante-pqp.png",
  },
  {
    id: 62,
    name: "Dispensador de cloro 3 pulg",
    category: "Dosificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Dosificadores",
    image: "/products/dispensador-de-cloro-3-pulg.png",
  },
  {
    id: 63,
    name: "Dosificador de cloro 3 En 1 OxyCl",
    category: "Dosificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Dosificadores",
    image: "/products/dosificador-de-cloro-3-en-1-oxycl.png",
  },
  {
    id: 64,
    name: "Dosificador de cloro Cisne flotante",
    category: "Dosificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Dosificadores",
    image: "/products/dosificador-de-cloro-cisne-flotante.png",
  },
  {
    id: 65,
    name: "Dosificador Quadex plus 4 EN 1 tubo flotante",
    category: "Dosificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Dosificadores",
    image: "/products/dosificador-quadex-plus-4-en-1-tubo-flotante.png",
  },
  {
    id: 66,
    name: "Dren de fondo 1.5 pulg Hayward",
    category: "Rejillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Rejillas",
    image: "/products/dren-de-fondo-1-5-pulg-hayward.png",
  },
  {
    id: 67,
    name: "Dren de fondo antivortex de 2 pulg Astrapool",
    category: "Rejillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Rejillas",
    image: "/products/dren-de-fondo-antivortex-de-2-pulg-astrapool.png",
  },
  {
    id: 68,
    name: "Electrobomba Centrífuga Fix de 1HP/1.5HP a 110v",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-centrifuga-fix-de-1hp-1-5hp-a-110v.jpg",
  },
  {
    id: 69,
    name: "Electrobomba Emaux SPH Superpower",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-emaux-sph-superpower.jpg",
  },
  {
    id: 70,
    name: "Electrobomba Emaux SS",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-emaux-ss.jpg",
  },
  {
    id: 71,
    name: "Electrobomba PKM Pedrollo",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-pkm-pedrollo.jpg",
  },
  {
    id: 72,
    name: "Electrobomba Silver de 0.75HP/1HP/1.5HP A 110V/220V",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-silver-de-0-75hp-1hp-1-5hp-a-110v-220v.jpg",
  },
  {
    id: 73,
    name: "Electrobomba sumergible de 4 pulg Pedrollo",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-sumergible-de-4-pulg-pedrollo.jpg",
  },
  {
    id: 74,
    name: "Electrobomba Sumergible TOP Pedrollo",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-sumergible-top-pedrollo.jpg",
  },
  {
    id: 75,
    name: "Electrobomba Supra 2HP/2.5HP/3HP A 220V",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-supra-2hp-2-5hp-3hp-a-220v.jpg",
  },
  {
    id: 76,
    name: "Electrobomba venus de 1HP/2HP a 110v",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/electrobomba-venus-de-1hp-2hp-a-110v.jpg",
  },
  {
    id: 77,
    name: "Equipo hidroneumático Pedrollo",
    category: "Bombas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Bombas",
    image: "/products/equipo-hidroneumatico-pedrollo.jpg",
  },
  {
    id: 78,
    name: "Escalera 3 peldaños para piscina",
    category: "Escaleras",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Escaleras",
    image: "/products/escalera-3-peldanos-para-piscina.png",
  },
  {
    id: 79,
    name: "Espuma para jacuzzi 1/2 galón L&M",
    category: "Jacuzzis",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Jacuzzis",
    image: "/products/espuma-para-jacuzzi-1-2-galon-l-y-m.png",
  },
  {
    id: 80,
    name: "Filtro cartucho carbón activado Block 2.5&#215;20.5 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-carbon-activado-block-2-5-y-215-20-5-purikor.png",
  },
  {
    id: 81,
    name: "Filtro cartucho CF200 MAN+2UNIV Emaux",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-cf200-man-2univ-emaux.png",
  },
  {
    id: 82,
    name: "Filtro cartucho de carbón activado granular (GAC) 2.5&#215;20 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-carbon-activado-granular-gac-2-5-y-215-20-purikor.png",
  },
  {
    id: 83,
    name: "Filtro cartucho de carbón activado granular (GAC) 4.5&#215;10 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-carbon-activado-granular-gac-4-5-y-215-10-purikor.png",
  },
  {
    id: 84,
    name: "Filtro cartucho de carbón activado granular (GAC) 4.5&#215;20 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-carbon-activado-granular-gac-4-5-y-215-20-purikor.png",
  },
  {
    id: 85,
    name: "Filtro cartucho de sedimentos plegado Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-sedimentos-plegado-purikor.png",
  },
  {
    id: 86,
    name: "Filtro cartucho de sedimentos Polipropileno Termofucionado 2.5x10x10 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-sedimentos-polipropileno-termofucionado-2-5x10x10-purikor.png",
  },
  {
    id: 87,
    name: "Filtro cartucho de sedimentos Polipropileno Termofucionado 2.5x20x20 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-sedimentos-polipropileno-termofucionado-2-5x20x20-purikor.png",
  },
  {
    id: 88,
    name: "Filtro cartucho de sedimentos polipropileno termofusionado 4.5x10x10 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-cartucho-de-sedimentos-polipropileno-termofusionado-4-5x10x10-purikor.png",
  },
  {
    id: 89,
    name: "Filtro de agua 3 capas",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-de-agua-3-capas.png",
  },
  {
    id: 90,
    name: "Filtro de arena para piscina astral V-50 Veico",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-de-arena-para-piscina-astral-v-50-veico.png",
  },
  {
    id: 91,
    name: "Filtro De Arena Para Piscina De 26 Pulgadas Panda",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-de-arena-para-piscina-de-26-pulgadas-panda.png",
  },
  {
    id: 92,
    name: "Filtro de arena para piscina FPD19T de 6 vías Panda",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtro-de-arena-para-piscina-fpd19t-de-6-vias-panda.png",
  },
  {
    id: 93,
    name: "Filtros cartucho de carbón activado Block Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtros-cartucho-de-carbon-activado-block-purikor.png",
  },
  {
    id: 94,
    name: "Filtros cartucho de sedimentos plegado 2.5x10x20 Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/filtros-cartucho-de-sedimentos-plegado-2-5x10x20-purikor.png",
  },
  {
    id: 95,
    name: "Generador de Cloro con Sal IntelliChlor Pentair",
    category: "Generadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Generadores",
    image: "/products/generador-de-cloro-con-sal-intellichlor-pentair.png",
  },
  {
    id: 96,
    name: "Generador Electrico De Vapor Para Sauna 12Kv Trifásico Oceanic",
    category: "Generadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Generadores",
    image: "/products/generador-electrico-de-vapor-para-sauna-12kv-trifasico-oceanic.png",
  },
  {
    id: 97,
    name: "Hidrojet 1 1/2 X 1 para jacuzzi",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/hidrojet-1-1-2-x-1-para-jacuzzi.png",
  },
  {
    id: 98,
    name: "Hipoclorito de calcio americano al 68% Hth",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/hipoclorito-de-calcio-americano-al-68-hth.png",
  },
  {
    id: 99,
    name: "Hipoclorito de calcio granulado Pluschlor",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/hipoclorito-de-calcio-granulado-pluschlor.png",
  },
  {
    id: 100,
    name: "Hipoclorito de Sodio 15% Pennclorito",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/hipoclorito-de-sodio-15-pennclorito.png",
  },
  {
    id: 101,
    name: "Inyector para piscina con membrana 1.5 pulg CMP",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/inyector-para-piscina-con-membrana-1-5-pulg-cmp.png",
  },
  {
    id: 102,
    name: "Kit analizador de cloro Y Ph para agua Panda",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/kit-analizador-de-cloro-y-ph-para-agua-panda.png",
  },
  {
    id: 103,
    name: "Kit analizador de Ph Y Cloro",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/kit-analizador-de-ph-y-cloro.png",
  },
  {
    id: 104,
    name: "Kit de prueba residencial para piscinas y spas Taylor",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/kit-de-prueba-residencial-para-piscinas-y-spas-taylor.png",
  },
  {
    id: 105,
    name: "Lampara Luz Led Extra Plana Para Piscina Rgb 24 W",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/lampara-luz-led-extra-plana-para-piscina-rgb-24-w.png",
  },
  {
    id: 106,
    name: "Limpiador en polvo 123",
    category: "Limpiadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Limpiadores",
    image: "/products/limpiador-en-polvo-123.png",
  },
  {
    id: 107,
    name: "Luz Led Sumergible 3000K 12W 12V",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/luz-led-sumergible-3000k-12w-12v.png",
  },
  {
    id: 108,
    name: "Manguera de vacío para piscinas Sunsolar",
    category: "Mangueras",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Mangueras",
    image: "/products/manguera-de-vacio-para-piscinas-sunsolar.png",
  },
  {
    id: 109,
    name: "Medidor Digital De Ph L&M",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/medidor-digital-de-ph-l-y-m.png",
  },
  {
    id: 110,
    name: "Membrana de ultrafiltracion repuesto Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/membrana-de-ultrafiltracion-repuesto-purikor.png",
  },
  {
    id: 111,
    name: "Modificador de dureza - Alka Dur Caneca",
    category: "Modificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Modificadores",
    image: "/products/modificador-de-dureza-alka-dur-caneca.png",
  },
  {
    id: 112,
    name: "Nasa estándar MaaaxClean",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/nasa-estandar-maaaxclean.png",
  },
  {
    id: 113,
    name: "Nasa para piscina Pool Net",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/nasa-para-piscina-pool-net.png",
  },
  {
    id: 114,
    name: "Nasa para piscina sencilla sacahojas WaterClear",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/nasa-para-piscina-sencilla-sacahojas-waterclear.png",
  },
  {
    id: 115,
    name: "Nasa tipo americana MaaaxClear",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/nasa-tipo-americana-maaaxclear.png",
  },
  {
    id: 116,
    name: "Nasa tipo bolsa Espumadora de hojas MaaaxClear",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/nasa-tipo-bolsa-espumadora-de-hojas-maaaxclear.png",
  },
  {
    id: 117,
    name: "Pasamanos para piscina",
    category: "Escaleras",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Escaleras",
    image: "/products/pasamanos-para-piscina.png",
  },
  {
    id: 118,
    name: "PortaFiltro azul 10 pulg",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/portafiltro-azul-10-pulg.png",
  },
  {
    id: 119,
    name: "prueba 1",
    category: "Accesorios",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Accesorios",
    image: "/products/prueba-1.png",
  },
  {
    id: 120,
    name: "Purificador De Agua 6 Etapas Ultrafiltracion+Uv+Alcalino Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/purificador-de-agua-6-etapas-ultrafiltracion-uv-alcalino-purikor.png",
  },
  {
    id: 121,
    name: "Reactivo",
    category: "Reactivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reactivos",
    image: "/products/reactivo.png",
  },
  {
    id: 122,
    name: "Reactivo Orthotolidina Star Químicos y Accesorios S.A.S",
    category: "Reactivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reactivos",
    image: "/products/reactivo-orthotolidina-star-quimicos-y-accesorios-s-a-s.png",
  },
  {
    id: 123,
    name: "Red saca hojas tipo bolsa Panda",
    category: "Redes",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Redes",
    image: "/products/red-saca-hojas-tipo-bolsa-panda.png",
  },
  {
    id: 124,
    name: "Reflector",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/reflector.png",
  },
  {
    id: 125,
    name: "Reflector",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/reflector-2.png",
  },
  {
    id: 126,
    name: "Reflector",
    category: "Luces",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Luces",
    image: "/products/reflector-3.png",
  },
  {
    id: 127,
    name: "Reflector de luz LED blanca 12V 1W",
    category: "Luces",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Luces",
    image: "/products/reflector-de-luz-led-blanca-12v-1w.png",
  },
  {
    id: 128,
    name: "Reflector para Piscina TP100 8 WATTS Emaux",
    category: "Reflectores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reflectores",
    image: "/products/reflector-para-piscina-tp100-8-watts-emaux.png",
  },
  {
    id: 129,
    name: "Reflector para piscina y jacuzzi Ion de 7W/12V",
    category: "Luces",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Luces",
    image: "/products/reflector-para-piscina-y-jacuzzi-ion-de-7w-12v.png",
  },
  {
    id: 130,
    name: "Rejilla de fondo anti atrapamiento para piscinas Hayward",
    category: "Rejillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Rejillas",
    image: "/products/rejilla-de-fondo-anti-atrapamiento-para-piscinas-hayward.png",
  },
  {
    id: 131,
    name: "Repuesto reactivo Taylor",
    category: "Reactivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Reactivos",
    image: "/products/repuesto-reactivo-taylor.png",
  },
  {
    id: 132,
    name: "Sistema De Filtración 3 Etapas Purikor",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/sistema-de-filtracion-3-etapas-purikor.png",
  },
  {
    id: 133,
    name: "Soda cáustica líquida Álcalis",
    category: "Químicos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Químicos",
    image: "/products/soda-caustica-liquida-alcalis.png",
  },
  {
    id: 134,
    name: "Super AlgaGuard 60% Hth",
    category: "Alguicidas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Alguicidas",
    image: "/products/super-algaguard-60-hth.png",
  },
  {
    id: 135,
    name: "Super clarificador de agua para piscinas Star Blue",
    category: "Clarificadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Clarificadores",
    image: "/products/super-clarificador-de-agua-para-piscinas-star-blue.png",
  },
  {
    id: 136,
    name: "SuperBlue alguicida Cloridex",
    category: "Alguicidas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Alguicidas",
    image: "/products/superblue-alguicida-cloridex.png",
  },
  {
    id: 137,
    name: "Superclor 91% x Kg",
    category: "Cloro Granulado",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Cloro Granulado",
    image: "/products/superclor-91-x-kg.jpg",
  },
  {
    id: 138,
    name: "Tanque Polyglass 10&#215;54 pulgadas Puriplus",
    category: "Tanques",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Tanques",
    image: "/products/tanque-polyglass-10-y-215-54-pulgadas-puriplus.png",
  },
  {
    id: 139,
    name: "Tanque Polyglass 8&#215;44 pulgadas Puriplus",
    category: "Tanques",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Tanques",
    image: "/products/tanque-polyglass-8-y-215-44-pulgadas-puriplus.png",
  },
  {
    id: 140,
    name: "Tapón para boquilla de succión 2 pulg",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/tapon-para-boquilla-de-succion-2-pulg.png",
  },
  {
    id: 141,
    name: "Tapón rejilla toma pared",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/tapon-rejilla-toma-pared.png",
  },
  {
    id: 142,
    name: "Terminal",
    category: "Mangueras",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Mangueras",
    image: "/products/terminal.png",
  },
  {
    id: 143,
    name: "Tiras de prueba para salinidad en el agua Aquachek",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/tiras-de-prueba-para-salinidad-en-el-agua-aquachek.png",
  },
  {
    id: 144,
    name: "Tirillas reactivas de prueba 7 en 1 para piscina x50 Maaaxclor",
    category: "Medidores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Medidores",
    image: "/products/tirillas-reactivas-de-prueba-7-en-1-para-piscina-x50-maaaxclor.png",
  },
  {
    id: 145,
    name: "Titulo",
    category: "Adhesivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Adhesivos",
    image: "/products/titulo.png",
  },
  {
    id: 146,
    name: "Titulo",
    category: "Adhesivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Adhesivos",
    image: "/products/titulo-2.png",
  },
  {
    id: 147,
    name: "Titulo",
    category: "Adhesivos",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Adhesivos",
    image: "/products/titulo-3.png",
  },
  {
    id: 148,
    name: "Toma de aspirar Astral",
    category: "Boquillas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Boquillas",
    image: "/products/toma-de-aspirar-astral.png",
  },
  {
    id: 149,
    name: "Trampa de cabello",
    category: "Filtros",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Filtros",
    image: "/products/trampa-de-cabello.png",
  },
  {
    id: 150,
    name: "Transformador de aislamiento para piscinas TLH 25 Magom",
    category: "Transformadores",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Transformadores",
    image: "/products/transformador-de-aislamiento-para-piscinas-tlh-25-magom.png",
  },
  {
    id: 151,
    name: "Válvula lateral 2 pulg filtro mod. LWT 750/900 Emaux",
    category: "Válvulas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Válvulas",
    image: "/products/valvula-lateral-2-pulg-filtro-mod-lwt-750-900-emaux.png",
  },
  {
    id: 152,
    name: "Válvulas",
    category: "Válvulas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Válvulas",
    image: "/products/valvulas.png",
  },
  {
    id: 153,
    name: "Válvulas",
    category: "Válvulas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Válvulas",
    image: "/products/valvulas-2.png",
  },
  {
    id: 154,
    name: "Válvulas",
    category: "Válvulas",
    price: null,
    unit: "Precio por definir",
    stock: 1,
    tag: "Válvulas",
    image: "/products/valvulas-3.png",
  },
];

export const categories = [
  "Todos",
  ...Array.from(new Set(products.map((product) => product.category))).sort(),
];
